EXTRN mat:byte
EXTRN mwidth:byte
EXTRN mheight:byte

; DATASEG SEGMENT PARA PUBLIC 'DATA'
;     w DB 0
;     h DB 0
; DATASEG ENDS

CSEG SEGMENT PARA PUBLIC 'CODE'
    ASSUME CS:CSEG, DS:DATASEG
code:
    MOV AX, DATASEG
    MOV DS, AX

    MOV AX, SEG mat
    MOV ES, AX
    MOV BH, ES:mat

CSEG ENDS